name = "ACE3"
prefix = "ace"
author = "ACE-Team"
files = [
    "*.dll",
    "*.so",
    "mod.cpp",
    "README.md",
    "docs/README_DE.md",
    "docs/README_PL.md",
    "AUTHORS.txt",
    "LICENSE",
    "logo_ace3_ca.paa",
    "meta.cpp"
]
headerexts = [
    "version={{git \"id 8\"}}"
]
keyname = "ace_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "!launchableoptionals",
    "@zip ace3_{{semver.major}}.{{semver.minor}}.{{semver.patch}}"
]

[scripts]
    [scripts.launchableoptionals]
    steps_linux = [
        #"if [ $(dirname {{target}}) == 'optionals' ]; then mkdir @ace_{{addon}}; mv {{target}} @ace_{{addon}}/{{target}}; fi"
    ]
    steps_windows = [

    ]
    show_output = true
    foreach = true
    #parallel = true

